FROM ubuntu:18.04

MAINTAINER Kim Ellefsen

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y nginx wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && echo "daemon off;" >> /etc/nginx/nginx.conf

RUN chown -R www-data:www-data /var/www/html

ADD default.local /etc/nginx/sites-available/default

EXPOSE 80
CMD ["nginx"]
