version: "3"
services:
  nginx:
    build:
      context: ./support
      dockerfile: Dockerfile.nginx
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
  php:
    build:
      context: ./support
      dockerfile: Dockerfile.php73
    volumes:
    - ./:/var/www/html
  redis:
    image: redis:alpine
